name             'reinstall_chef'
maintainer       'JamesJJ'
maintainer_email 'JamesJJ@users.noreply.github.com'
license          'MIT'
description      'Re-install chef'
long_description      'Re-install chef'
version          '0.1.3'
