name             'reinstall_chef'
maintainer       'github@jamesjj.net'
maintainer_email 'github@jamesjj.net'
license          'MIT'
description      'Re-install chef'
long_description      'Re-install chef'
version          '0.1.2'
